# build/Dockerfileを使って、イメージ densukest/xampp-devenv:latest をビルドする
# ビルド後イメージを densukest/xampp-devenv:latest としてpushする

name: Docker Image CI(ビルドテスト)

on:
    push:
        branches-ignore:
        - release/*
    pull_request:
        branches-ignore:
        - release/*
    workflow_dispatch: # 手動実行

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: チェックアウト
          uses: actions/checkout@v4
        - name: "docker buildの準備"
          uses: docker/setup-buildx-action@v3
        - name: "dockerへのログイン"
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: "イメージのビルド"
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./build/Dockerfile
            platforms: linux/amd64
            push: true
            tags: densukest/xampp-devenv:latest

